[build]
  command = """
    cd frontend && npm install && npm run build && cd ../backend && python -m pip install --upgrade pip && pip install -r requirements.txt
  """
  publish = "frontend/build"
  functions = "backend"

[build.environment]
  NODE_VERSION = "16"
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "backend"
  node_bundler = "esbuild"
  included_files = ["backend/requirements.txt", "backend/runtime.txt"]