services:
  - type: web
    name: shl-assessment-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 16.0.0
    rootDir: frontend
