services:
  - type: web
    name: shl-assessment-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/wsgi.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

  - type: web
    name: shl-assessment-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 16.0.0
    rootDir: frontend
